version: "3.8"

services:
  db:
    image: postgres:14.6-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todolist_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 3

  api:
    image: ${DOCKER_HUB_USERNAME}/todolist:${TAG_NAME}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./todolist/:/app/todolist
      - ./core/:/app/core

  collect_static:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    command: python3 manage.py collectstatic -c --no-input
    volumes:
      - django_static:/opt/static

  front:
    image: sermalenk/skypro-front:lesson-36
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - django_static:/usr/share/nginx/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  todolist_pg_data:
    driver: local
  django_static:
    driver: local
